// Copyright (c) Alexandre Mutel. All rights reserved.
// This file is licensed under the BSD-Clause 2 license.
// See the license.txt file in the project root for more information.

using System.Collections.Generic;
using System.Text.Json;
using System.Text.RegularExpressions;
using Markdig.Extensions.Tables;

namespace Markdig.Tests;

[TestFixture]
public class TestGfmPipeTableDifferential
{
    private static readonly MarkdownPipeline Strict = new MarkdownPipelineBuilder()
        .UsePipeTables(new PipeTableOptions { UseGfmRules = true }).Build();
    private static readonly MarkdownPipeline Tracked = new MarkdownPipelineBuilder()
        .UsePipeTables(new PipeTableOptions { UseGfmRules = true }).EnableTrackTrivia().Build();

    // Native cmark-gfm output, not output generated by Markdig. See the tool's
    // README for provenance, regeneration and the limits of subtree comparisons.
    public static IEnumerable<TestCaseData> NativeCases()
    {
        using var stream = typeof(TestGfmPipeTableDifferential).Assembly.GetManifestResourceStream(
            "Markdig.Tests.Specs.GfmPipeTableDifferential.json")!;
        using var document = JsonDocument.Parse(stream);
        int index = 0;
        foreach (var item in document.RootElement.EnumerateArray())
        {
            yield return new TestCaseData(item.GetProperty("input").GetString(),
                item.GetProperty("expected").GetString(), item.GetProperty("tableOnly").GetBoolean())
                .SetName($"NativeGfm_{item.GetProperty("group").GetString()}_{++index:D4}");
        }
    }

    [TestCaseSource(nameof(NativeCases))]
    public void MatchesNativeOutput(string markdown, string expected, bool tableOnly)
    {
        var actual = Normalize(Markdown.ToHtml(markdown, Strict));
        Assert.That(tableOnly ? Tables(actual) : actual, Is.EqualTo(tableOnly ? Tables(expected) : expected), markdown);
        // Trivia mode deliberately preserves whitespace outside tables, unlike
        // cmark-gfm. Table presence, cell text, alignment and row shape must agree.
        Assert.That(Tables(Normalize(Markdown.ToHtml(markdown, Tracked))), Is.EqualTo(Tables(expected)), markdown);
    }

    private static string Normalize(string html) => Regex.Replace(html.Replace("\r\n", "\n"),
        @"<li>\n?(?=<(?:h[1-6]|table|blockquote|pre|ul|ol|hr|p)[ >])", "<li>\n").Trim();

    private static string Tables(string html) => string.Join("\n",
        Regex.Matches(html, @"(?s)<table>.*?</table>").Select(match => match.Value));

    public static IEnumerable<TestCaseData> NormalizationCases()
    {
        foreach (var test in NativeCases())
        {
            if (test.TestName!.StartsWith("NativeGfm_backslash_", StringComparison.Ordinal)
                || test.TestName.StartsWith("NativeGfm_inline-focused_", StringComparison.Ordinal))
            {
                yield return new TestCaseData(test.Arguments[0]).SetName(test.TestName.Replace("NativeGfm_", "NormalizeGfm_"));
            }
        }
    }

    [TestCaseSource(nameof(NormalizationCases))]
    public void NormalizationPreservesNativeInlineSemantics(string markdown)
    {
        var normalized = Markdown.Normalize(markdown, pipeline: Strict);
        Assert.That(Markdown.ToHtml(normalized, Strict), Is.EqualTo(Markdown.ToHtml(markdown, Strict)));
        Assert.That(Markdown.Normalize(normalized, pipeline: Strict), Is.EqualTo(normalized));
    }
}
