name: ci

on:
  push:
    paths-ignore:
    - 'site/**'
    - 'img/**'
    - '*.md'
    - '*.txt'
  pull_request:

jobs:
  build:
    permissions:
      id-token: write
      actions: write
      contents: write
    runs-on: 'ubuntu-latest'
    steps:
      - name: "Build, Test, Pack and Publish"
        uses: xoofx/.github/.github/actions/dotnet-releaser-action@main
        with:
          dotnet-version: |
            6.0
            8.0
            10.0
